service: peanut-butter-box-client
  
configValidationMode: error

custom:
  client:
    bucketName: ${self:provider.stage}.peanutbutterbox.org
    distributionFolder: out

provider:
  name: aws
  stage: dev

plugins:
  - serverless-finch
