service: peanut-butter-box-client
  
configValidationMode: error

custom:
  bucketNames:
    dev: dev.peanutbutterbox.org
    prod: peanutbutterbox.org
  client:
    bucketName: ${self:custom.bucketNames.${opt:stage}}
    distributionFolder: out

provider:
  name: aws
  stage: ${opt:stage}

plugins:
  - serverless-finch
